%YAML 1.2
---
default:
    image: "python:3.8"
    before_script:
        - pip3 install 'tox < 3.15'

variables:
    TOXENV: ${CI_JOB_NAME}

.job_template: &job_base
    script:
        - tox

.reports_template: &job_reports
    extends: .job_template
    coverage: '/TOTAL.*\s+(\d+%)$/'
    artifacts:
    reports:
        junit:
            - *.junit.xml

lint:
    extends: .job_template
style:
    extends: .job_template
security:
    extends: .job_template
pkg:
    extends: .job_template
py38:
    extends: .reports_template
py37:
    image: "python:3.7"
    extends: .reports_template
py36:
    image: "python:3.6"
    extends: .reports_template
py39:
    image: "python:rc"
    extends: .reports_template
    allow_failure: true

